
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:  
   port: 587
   host: smtp.gmail.com
   username: ssbasavaraj369@gmail.com
   password: retjejccydecndfu